### ISSUE TITLE
Replace 'WightDev' with something more generic

### ISSUE THREAD

**Issue by bioshazard** [eflip/XV#1]
This is the current default installation on the new release from

http://littlefootcms.com/files/download/littlefoot.zip

However, there is a big "WightDev" header that needs to be more generic

http://dev5.bioshazard.com/installtest/littlefoot/index.php/

All you need to do is push the update to the XV skin, merge to master, and run the release command on littlefootcms.com.

**Comment by wightmike** [comment]
WightDev was replaced with Littlefoot
